FROM centos:7
MAINTAINER Takumi ICHIKAWA <@>
ARG STAR_VERSION=2.7.0e
RUN set -x && yum update -y && yum install -y wget ImageMagick ImageMagick-devel && yum clean all && \
    cd /tmp && \
    wget https://github.com/alexdobin/STAR/archive/${STAR_VERSION}.tar.gz && \
    tar -xzf ${STAR_VERSION}.tar.gz && \
    cd STAR-${STAR_VERSION}/bin/Linux_x86_64 && \
    cp ./* /usr/bin/ && \
    cd /tmp && \
    rm -rf ${STAR_VERSION}.tar.gz && \
    rm -rf ./STAR-${STAR_VERSION}
